### PR TITLE
Fix a panic on spinner thread shutdown and a compile error

### PR DESCRIPTION
**Pull request by c-jiph**
Hi, I've been using this in a small project of mine and ran into some issues which this PR fixes. I'm hoping you will find these changes useful too.

My main problem was a panic when closing my application when the spinner is running. The other is a compilation issue, which I don't fully understand (I'm new to Rust) but I guess it may come from a newer version of the language. See the commits for details.

### CODE REVIEW

**Comment by otov4its** [comment]
Hi! Your PR looks quite legitimate. Thanks.
I'll merge it and fix some dependency updates issues.

> Presumably this is due to a newer version of Rust?

I think it's due to dependency updates. There is no Cargo.lock file yet.

**Comment by otov4its** [comment]
New version 0.1.3 released

**Comment by c-jiph** [comment]
Great! Thanks for merging and also for making the overall project OSS in the first place.

> I think it's due to dependency updates. There is no Cargo.lock file yet.

My understanding is libraries, which I think this would qualify as, should not have their Cargo.lock file checked in: https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html.

It does mean as a library maintainer though you're forever on a treadmill, fixing updates in dependencies though.

**Comment by otov4its** [comment]
Oh, indeed, you are absolutely right. A new version v0.1.4 released. Thank you!

**Pull request merged**
